colourful: true

#Folder color override
filekinds:
  directory:
    foreground: Cyan

# Exact-name overrides
filenames:
  README:
    filename:
      foreground: White
      is_bold: true
      is_underline: false

  README.md:
    filename:
      foreground: White
      is_dimmed: true
      is_bold: true
      is_underline: false

  LICENSE:
    filename:
      foreground: White
      is_dimmed: true
      is_bold: true
      is_underline: false

  ".backups":
    filename:
      foreground: White
      is_dimmed: false
      is_italic: true
  ".git":
    filename:
      foreground: White
      is_dimmed: false
      is_italic: true
  ".github":
    filename:
      foreground: White
      is_dimmed: false
      is_italic: true
  ".config":
    filename:
      foreground: White
      is_dimmed: false
      is_italic: true
  ".cache":
    filename:
      foreground: White
      is_dimmed: false
      is_italic: true
  ".vscode":
    filename:
      foreground: White
      is_dimmed: false
      is_italic: true
  ".idea":
    filename:
      foreground: White
      is_dimmed: false
      is_italic: true
  ".venv":
    filename:
      foreground: White
      is_dimmed: false
      is_italic: true
  ".mypy_cache":
    filename:
      foreground: White
      is_dimmed: false
      is_italic: true
  ".pytest_cache":
    filename:
      foreground: White
      is_dimmed: false
      is_italic: true
  "__pycache__":
    filename:
      foreground: White
      is_dimmed: false
      is_italic: true

  "__init__.py":
    filename:
      foreground: BrightWhite
      is_italic: true
      is_underline: false

file_type:
  build:
    foreground: Yellow
    is_bold: true
    is_underline: false

# Extension-wide styling
#extensions:
#  md:
#    filename:
#      foreground: White
#      is_underline: false
