---
- name: Ensure ~/.config exists (safety)
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory

# DO NOT remove/copy config anymore; ~/.config is a worktree managed by git.

- name: Check if nvim is available
  command: bash -lc 'command -v nvim >/dev/null && echo present || echo missing'
  register: nvim_check
  changed_when: false
  failed_when: false

- name: Ensure Vim undodir exists
  file:
    path: "{{ ansible_env.HOME }}/.vim/undodir"
    state: directory
    mode: "0755"

- name: Preinstall Neovim plugins via lazy.nvim (headless)
  when: nvim_check.stdout == 'present' and not ansible_check_mode
  shell: |
    nvim --headless "+Lazy! sync" "+qa"
  args: { executable: /bin/bash }
  environment:
    PATH: "{{ ansible_env.PATH }}:/opt/homebrew/bin:/usr/local/bin"
  changed_when: false

- name: Build LuaSnip jsregexp (if plugin is present)
  when: not ansible_check_mode
  shell: |
    [ -d "{{ ansible_env.HOME }}/.local/share/nvim/lazy/LuaSnip" ] && \
    make -C "{{ ansible_env.HOME }}/.local/share/nvim/lazy/LuaSnip" install_jsregexp || true
  args: { executable: /bin/bash }
  changed_when: false

- name: Install Mason LSP servers (lua, python, typescript)
  when: nvim_check.stdout == 'present' and not ansible_check_mode
  shell: |
    nvim --headless \
      "+MasonInstall lua-language-server python-lsp-server typescript-language-server" \
      "+qa" || true
  args: { executable: /bin/bash }
  environment:
    PATH: "{{ ansible_env.PATH }}:/opt/homebrew/bin:/usr/local/bin"
  changed_when: false
