- name: Remove existing nvim config (if any)
  file:
    path: "{{ lookup('env','HOME') }}/.config/nvim"
    state: absent

- name: Ensure config dir exists
  file:
    path: "{{ lookup('env','HOME') }}/.config"
    state: directory

- name: Clone helix repo to cache
  git:
    repo: "{{ helix_repo_url }}"
    dest: "{{ helix_cache_path }}"
    version: "{{ helix_repo_branch }}"
    depth: 1
    update: yes

- name: Copy helix nvim to ~/.config/nvim
  copy:
    src: "{{ helix_cache_path }}/nvim/"
    dest: "{{ lookup('env','HOME') }}/.config/nvim/"
    remote_src: yes
    mode: preserve