---
- name: Only run on macOS
  meta: end_host
  when: ansible_system != "Darwin"

# Find Homebrew
- name: Detect Homebrew (Apple Silicon path)
  stat:
    path: /opt/homebrew/bin/brew
  register: brew_path_opt

- name: Detect Homebrew (Intel path)
  stat:
    path: /usr/local/bin/brew
  register: brew_path_usr

- name: Fail if Homebrew not found
  fail:
    msg: "Homebrew not found. Run the base macOS play first."
  when: not brew_path_opt.stat.exists and not brew_path_usr.stat.exists

- name: Set brew_bin path fact
  set_fact:
    brew_bin: >-
      {{ '/opt/homebrew/bin/brew' if brew_path_opt.stat.exists else '/usr/local/bin/brew' }}

# Compute final list, honoring host-level skips
- name: Build desktop cask target list
  set_fact:
    desktop_casks_targets: "{{ (desktop_casks | default([])) | difference(desktop_casks_skip | default([])) }}"

- name: Install/overwrite casks per item with graceful fallback
  block:
    - name: Install/overwrite {{ cask }} (force)
      community.general.homebrew_cask:
        name: "{{ cask }}"
        state: present
        path: "{{ brew_bin }}"
        install_options: ['force']
  rescue:
    - name: Accept external app for {{ cask }} (skip)
      community.general.homebrew_cask:
        name: "{{ cask }}"
        state: present
        path: "{{ brew_bin }}"
        accept_external_apps: true
  loop: "{{ desktop_casks_targets }}"
  loop_control: { loop_var: cask, label: "{{ cask }}" }
