---
- name: Only run on macOS
  meta: end_host
  when: ansible_system != "Darwin"

- name: Prepare temp + mount dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ ansible_env.TMPDIR | default('/tmp') }}/apple_sf_fonts"
    - "{{ ansible_env.TMPDIR | default('/tmp') }}/apple_sf_fonts/mnt"

# Loop per font by including a sub-task file
- name: Process Apple SF font
  include_tasks: install_from_dmg.yml
  loop: "{{ apple_sf_fonts }}"
  loop_control:
    loop_var: font
    label: "{{ font.name }}"
  tags: ['fonts']
