---
# Cache the helix repo (idempotent)
- name: Clone helix to cache
  git:
    repo: "{{ helix_repo_url }}"
    dest: "{{ helix_cache_path }}"
    version: "{{ helix_repo_branch }}"
    depth: 1
    update: yes

- name: Ensure ~/.config exists
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    mode: "0755"

- name: Set dotfiles source dirs
  set_fact:
    df_home_src:   "{{ helix_cache_path }}/{{ helix_dotfiles_dir }}/home"
    df_config_src: "{{ helix_cache_path }}/{{ helix_dotfiles_dir }}/config/.config"

- name: Copy home files (stubs, .zshrc, etc.)
  when: df_home_src is exists
  copy:
    src:  "{{ df_home_src }}/"
    dest: "{{ ansible_env.HOME }}/"
    remote_src: yes
    mode: preserve

- name: Copy .config tree (XDG configs)
  when: df_config_src is exists
  copy:
    src:  "{{ df_config_src }}/"
    dest: "{{ ansible_env.HOME }}/.config/"
    remote_src: yes
    mode: preserve
